version: "3.8"

services:
  db:
    image: mariadb:latest
    container_name: maria_pose
    environment:
      MARIADB_ROOT_PASSWORD: 2808
      MARIADB_DATABASE: fruits
      MARIADB_USER: user
      MARIADB_PASSWORD: 2808
    ports:
      - "3306:3306"
    networks:
      - my_network

  api:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    image: fruits:dev
    container_name: fruits-api-dev
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - my_network

networks:
  my_network: